package datos.edificio;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

/**
 * Edificio generated by MyEclipse Persistence Tools
 */
public class Edificio extends AbstractEdificio implements java.io.Serializable {

	// Constructors
	private static final long serialVersionUID = 884077160886671787L;

	/** default constructor */
	public Edificio() {
	}

	public Edificio(Integer idEdificio) {
		this.setIdEdificio(idEdificio);
	}
	
	/** minimal constructor */
	public Edificio(Integer idEdificio, String descripcion) {
		super(idEdificio, descripcion);
	}

	/** full constructor */
	public Edificio(Integer idEdificio, String descripcion,
			String observaciones, Short dptoCantidad, Set inmuebles) {
		super(idEdificio, descripcion, observaciones, dptoCantidad, inmuebles);
	}

}
