package datos.contrato_novedad_cobro;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import app.beans.NovedadTipo;
import app.beans.Utiles;

import datos.contrato.Contrato;
import datos.persona.Persona;

/**
 * ContratoNovedadCobro generated by MyEclipse Persistence Tools
 */
public class ContratoNovedadCobro 
	extends AbstractContratoNovedadCobro
	implements java.io.Serializable {

	private static final long serialVersionUID = -4474612437098114163L;
	
	// Atributos no persistidos - calculados
	private Double saldo;
	private Double pagado; // Es lo que le pagué al propietario
	private String periodoCuota;
	private String movimiento;
	
	// Constructors

	/** default constructor */
	public ContratoNovedadCobro() {
	}

	/** minimal constructor */
	public ContratoNovedadCobro(Integer idContratoNovedadCobro,
			Contrato contrato, Persona persona, Short idNovedadTipo,
			Date fechaAlta) {
		super(idContratoNovedadCobro, contrato, persona, idNovedadTipo, fechaAlta);
	}

	/** full constructor */
	public ContratoNovedadCobro(Integer idContratoNovedadCobro,
			Contrato contrato, Persona persona, Short idNovedadTipo,
			Short periodoMes, Short periodoAnio, Short contratoCuota,
			Double monto, Date fechaVencimiento, Date fechaAlta, String observaciones,
			Short impuestoId, Short impuestoCuota, Short impuestoAnio) {
		
		super(idContratoNovedadCobro, contrato, persona, idNovedadTipo,
				periodoMes, periodoAnio, contratoCuota, monto,
				fechaVencimiento, fechaAlta, observaciones, 
				impuestoId, impuestoCuota, impuestoAnio);
	}
	
	
	public String getPeriodoCuota() {
		
		String salida = "";
		
		try {
			if (this.getPeriodoMes() != null && this.getPeriodoAnio() != null && this.getContratoCuota() != null) {
				salida = Utiles.convertirMes(this.getPeriodoMes()) + "-" + this.getPeriodoAnio() + ". Cuota:" + this.getContratoCuota(); 
			}
		} catch(NullPointerException npe) {
			// Para q no salga null
			// npe.printStackTrace();
		}
		this.periodoCuota = salida;
		return salida;
		
	}
	
	public void setPeriodoCuota(String periodoCuota) {
		this.periodoCuota = periodoCuota;
	}
	

	public Double getSaldo() {
		return saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}
	
	public Double getPagado() {
		return pagado;
	}

	public void setPagado(Double saldo) {
		this.pagado = saldo;
	}
	
	public String getMovimiento() {
		return NovedadTipo.getDescripcion(this.getIdNovedadTipo());
	}
	
}