package datos.recibo_cobro;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import datos.persona.Persona;
import datos.usuario.Usuario;

/**
 * AbstractReciboCobro generated by MyEclipse Persistence Tools
 */

public abstract class AbstractReciboCobro implements java.io.Serializable {

	// Fields

	private Integer idReciboCobro;

	private Usuario usuario;

	private Persona persona;

	private Integer numero;

	private Date fechaEmision;

	private String leyenda;

	private Set reciboCobroItems = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractReciboCobro() {
	}

	/** minimal constructor */
	public AbstractReciboCobro(	Integer idReciboCobro, 
								Usuario usuario,
								Persona persona, 
								Date fechaEmision) {
		this.idReciboCobro = idReciboCobro;
		this.usuario = usuario;
		this.persona = persona;
		this.fechaEmision = fechaEmision;
	}

	/** full constructor */
	public AbstractReciboCobro(Integer idReciboCobro, Usuario usuario,
			Persona persona, Integer numero, Date fechaEmision, String leyenda,
			Set reciboCobroItems) {
		this.idReciboCobro = idReciboCobro;
		this.usuario = usuario;
		this.persona = persona;
		this.numero = numero;
		this.fechaEmision = fechaEmision;
		this.leyenda = leyenda;
		this.reciboCobroItems = reciboCobroItems;
	}

	// Property accessors

	public Integer getIdReciboCobro() {
		return this.idReciboCobro;
	}

	public void setIdReciboCobro(Integer idReciboCobro) {
		this.idReciboCobro = idReciboCobro;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public String getLeyenda() {
		return this.leyenda;
	}

	public void setLeyenda(String leyenda) {
		this.leyenda = leyenda;
	}

	public Set getReciboCobroItems() {
		return this.reciboCobroItems;
	}

	public void setReciboCobroItems(Set reciboCobroItems) {
		this.reciboCobroItems = reciboCobroItems;
	}

}