package datos.recibo_cobro;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

import datos.persona.Persona;
import datos.usuario.Usuario;

/**
 * ReciboCobro generated by MyEclipse Persistence Tools
 */
public class ReciboCobro extends AbstractReciboCobro implements java.io.Serializable {
	
	private static final long serialVersionUID = 7471039250076959081L;
	
	// Atributos
	
	private double total;
	
	public double getTotal() {
		return total;
	}
	
	public void setTotal(double total) {
		this.total = total;
	}
	
	
	// Constructors

	/** default constructor */
	public ReciboCobro() {
	}

	/** minimal constructor */
	public ReciboCobro(Integer idReciboCobro, Usuario usuario, Persona persona,
			Date fechaEmision) {
		super(idReciboCobro, usuario, persona, fechaEmision);
	}

	/** full constructor */
	public ReciboCobro(Integer idReciboCobro, Usuario usuario, Persona persona,
			Integer numero, Date fechaEmision, String leyenda,
			Set reciboCobroItems) {
		super(idReciboCobro, usuario, persona, numero, fechaEmision, leyenda,
				reciboCobroItems);
	}

	
}
