package datos.inmueble;

import datos.edificio.Edificio;
import datos.localidad.Localidad;
import datos.persona.Persona;

/**
 * AbstractInmueble generated by MyEclipse Persistence Tools
 */

public abstract class AbstractInmueble implements java.io.Serializable {

	// Fields

	private Integer idInmueble;


	private Persona propietario;

	private Localidad localidad;

	private InmuebleTipo inmuebleTipo;
	
	private Edificio edificio;
	
	

	private String direccionCalle;

	private String direccionNro;

	private String direccionEdificio;

	private String direccionPiso;

	private String direccionDpto;

	private String observaciones;

	// Constructors

	/** default constructor */
	public AbstractInmueble() {
	}

	/** minimal constructor */
	public AbstractInmueble(	Integer idInmueble, 
								Localidad localidad,
								InmuebleTipo inmuebleTipo) {
		this.idInmueble = idInmueble;
		this.localidad = localidad;
		this.inmuebleTipo = inmuebleTipo;
	}

	/** full constructor */
	public AbstractInmueble(Integer idInmueble, 
							Persona propietario,
							Localidad localidad, 
							InmuebleTipo inmuebleTipo,
							Edificio edificio,
							String direccionCalle, 
							String direccionNro,
							String direccionEdificio, 
							String direccionPiso,
							String direccionDpto, 
							String observaciones) {
	
		this.idInmueble = idInmueble;
		
		this.propietario = propietario;
		this.localidad = localidad;
		this.inmuebleTipo = inmuebleTipo;
		this.edificio = edificio;
		
		this.direccionCalle = direccionCalle;
		this.direccionNro = direccionNro;
		this.direccionEdificio = direccionEdificio;
		this.direccionPiso = direccionPiso;
		this.direccionDpto = direccionDpto;
		this.observaciones = observaciones;
	}

	// Property accessors

	public Integer getIdInmueble() {
		return this.idInmueble;
	}

	public void setIdInmueble(Integer idInmueble) {
		this.idInmueble = idInmueble;
	}

	public Persona getPropietario() {
		return this.propietario;
	}

	public void setPropietario(Persona propietario) {
		this.propietario = propietario;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public InmuebleTipo getInmuebleTipo() {
		return this.inmuebleTipo;
	}

	public void setInmuebleTipo(InmuebleTipo inmuebleTipo) {
		this.inmuebleTipo = inmuebleTipo;
	}

	public Edificio getEdificio() {
		return this.edificio;
	}

	public void setEdificio(Edificio edificio) {
		this.edificio = edificio;
	}
	
	public String getDireccionCalle() {
		return this.direccionCalle;
	}

	public void setDireccionCalle(String direccionCalle) {
		this.direccionCalle = direccionCalle;
	}

	public String getDireccionNro() {
		return this.direccionNro;
	}

	public void setDireccionNro(String direccionNro) {
		this.direccionNro = direccionNro;
	}

	public String getDireccionEdificio() {
		return this.direccionEdificio;
	}

	public void setDireccionEdificio(String direccionEdificio) {
		this.direccionEdificio = direccionEdificio;
	}

	public String getDireccionPiso() {
		return this.direccionPiso;
	}

	public void setDireccionPiso(String direccionPiso) {
		this.direccionPiso = direccionPiso;
	}

	public String getDireccionDpto() {
		return this.direccionDpto;
	}

	public void setDireccionDpto(String direccionDpto) {
		this.direccionDpto = direccionDpto;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}