package datos.inmueble;

import datos.edificio.Edificio;
import datos.localidad.Localidad;
import datos.persona.Persona;

// Generated by MyEclipse Persistence Tools

/**
 * Inmueble generated by MyEclipse Persistence Tools
 */
public class Inmueble extends AbstractInmueble implements java.io.Serializable {

	private static final long serialVersionUID = -7443355980616504032L;
	
	// Atributos
	@SuppressWarnings("unused")
	private String direccion_completa;
	
	
	// Constructors

	/** default constructor */
	public Inmueble() {
	}

	/** minimal constructor */
	public Inmueble(Integer idInmueble, Localidad localidad,
			InmuebleTipo inmuebleTipo) {
		super(idInmueble, localidad, inmuebleTipo);
	}

	/** full constructor */
	public Inmueble(	Integer idInmueble, 
						Persona persona, 
						Localidad localidad,
						InmuebleTipo inmuebleTipo, 
						Edificio edificio,
						String direccionCalle,
						String direccionNro, 
						String direccionEdificio,
						String direccionPiso, 
						String direccionDpto, 
						String observaciones) {
		super(idInmueble, persona, localidad, inmuebleTipo, edificio, direccionCalle,
				direccionNro, direccionEdificio, direccionPiso, direccionDpto,
				observaciones);
		
		direccion_completa = "";
		
	}
	
	public void setDireccion_completa(String d) {this.direccion_completa = d;}
	public String getDireccion_completa() {
		
		String dir = "";
		
		dir = 	this.getDireccionCalle() + " " +
				this.getDireccionNro();
		
		if (this.getInmuebleTipo().getIdInmuebleTipo() == InmuebleTipo.InmuebleTipoCochera) {
			dir += " (Cochera)";
		} else if (!this.getDireccionDpto().equals("") || !this.getDireccionPiso().equals("")) {
			dir += " (Piso:" + this.getDireccionPiso() + "-Dpto.:" + this.getDireccionDpto() +")";		
		}
		
		return dir;
		
	}
	
}