package datos.factura_item;

import datos.contrato_novedad_factura.ContratoNovedadFactura;
import datos.factura.Factura;

/**
 * AbstractFacturaItem generated by MyEclipse Persistence Tools
 */

public abstract class AbstractFacturaItem implements java.io.Serializable {

	// Fields

	private Integer idFacturaItem;

	private Factura factura;

	private ContratoNovedadFactura contratoNovedadFactura;

	private Double monto;

	private String descripcion;

	private Short idItemTipo;

	// Constructors

	/** default constructor */
	public AbstractFacturaItem() {
	}

	/** minimal constructor */
	public AbstractFacturaItem(Factura factura, Double monto, Short idItemTipo) {
		this.factura = factura;
		this.monto = monto;
		this.idItemTipo = idItemTipo;
	}

	/** full constructor */
	public AbstractFacturaItem(	Factura factura, 
								ContratoNovedadFactura contratoNovedadFactura,
								Double monto, 
								String descripcion, 
								Short idItemTipo) {
		
		this.factura = factura;
		this.contratoNovedadFactura = contratoNovedadFactura;
		this.monto = monto;
		this.descripcion = descripcion;
		this.idItemTipo = idItemTipo;
	}

	// Property accessors

	public Integer getIdFacturaItem() {
		return this.idFacturaItem;
	}

	public void setIdFacturaItem(Integer idFacturaItem) {
		this.idFacturaItem = idFacturaItem;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public ContratoNovedadFactura getContratoNovedadFactura() {
		return this.contratoNovedadFactura;
	}

	public void setContratoNovedadFactura(ContratoNovedadFactura contratoNovedadFactura) {
		this.contratoNovedadFactura = contratoNovedadFactura;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Short getIdItemTipo() {
		return this.idItemTipo;
	}

	public void setIdItemTipo(Short idItemTipo) {
		this.idItemTipo = idItemTipo;
	}

}