package datos.factura_item;

import datos.contrato_novedad_factura.ContratoNovedadFactura;
import datos.factura.Factura;

// Generated by MyEclipse Persistence Tools

/**
 * FacturaItem generated by MyEclipse Persistence Tools
 */
public class FacturaItem extends AbstractFacturaItem implements java.io.Serializable {

	private static final long serialVersionUID = 3185752665694851760L;
	
	// Constructors

	/** default constructor */
	public FacturaItem() {
	}

	/** minimal constructor */
	public FacturaItem(Factura factura, Double monto, Short idItemTipo) {
		super(factura, monto, idItemTipo);
	}

	/** full constructor */
	public FacturaItem(	Factura factura,
						ContratoNovedadFactura contratoNovedadFactura,
						Double monto, 
						String descripcion, 
						Short idItemTipo) {
		super(factura, contratoNovedadFactura, monto, descripcion, idItemTipo);
	}

}
