package datos.persona;

import java.util.Date;

import datos.localidad.Localidad;

/**
 * AbstractPersona generated by MyEclipse Persistence Tools
 */

public abstract class AbstractPersona implements java.io.Serializable {

	// Fields

	private Integer idPersona;

	private Localidad localidad;

	private String apellido;

	private String nombres;

	private Short idDocumentoTipo;

	private Long documentoNro;

	private Date fechaNacimiento;

	private String direccion;

	private Short idInscripcionIva;
	private Short idInscripcionGanancias;

	private String cuit;

	private String telefono;

	private String celular;

	private String mail;

	private String razonSocial;

	private Date fechaAlta;

	private Short idPersonaTipo;

	private String sexo;

	private String observaciones;

	// Constructors

	/** default constructor */
	public AbstractPersona() {
	}

	/** minimal constructor */
	public AbstractPersona(Integer idPersona, String apellido, String nombres,
			Short idDocumentoTipo, Long documentoNro, Short idInscripcionIva,
			Short idPersonaTipo, String sexo, Short idInscripcionGanancias) {
		this.idPersona = idPersona;
		this.apellido = apellido;
		this.nombres = nombres;
		this.idDocumentoTipo = idDocumentoTipo;
		this.documentoNro = documentoNro;
		this.idInscripcionIva = idInscripcionIva;
		this.idPersonaTipo = idPersonaTipo;
		this.sexo = sexo;
		this.idInscripcionGanancias = idInscripcionGanancias;
	}

	/** full constructor */
	public AbstractPersona(Integer idPersona, Localidad localidad,
			String apellido, String nombres, Short idDocumentoTipo,
			Long documentoNro, Date fechaNacimiento, String direccion,
			Short idInscripcionIva, String cuit, String telefono,
			String celular, String mail, String razonSocial, Date fechaAlta,
			Short idPersonaTipo, String sexo, String observaciones, Short idInscripcionGanancias) {
		this.idPersona = idPersona;
		this.localidad = localidad;
		this.apellido = apellido;
		this.nombres = nombres;
		this.idDocumentoTipo = idDocumentoTipo;
		this.documentoNro = documentoNro;
		this.fechaNacimiento = fechaNacimiento;
		this.direccion = direccion;
		this.idInscripcionIva = idInscripcionIva;
		this.cuit = cuit;
		this.telefono = telefono;
		this.celular = celular;
		this.mail = mail;
		this.razonSocial = razonSocial;
		this.fechaAlta = fechaAlta;
		this.idPersonaTipo = idPersonaTipo;
		this.sexo = sexo;
		this.observaciones = observaciones;
		this.idInscripcionGanancias = idInscripcionGanancias;
	}

	// Property accessors

	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public Short getIdDocumentoTipo() {
		return this.idDocumentoTipo;
	}

	public void setIdDocumentoTipo(Short idDocumentoTipo) {
		this.idDocumentoTipo = idDocumentoTipo;
	}

	public Long getDocumentoNro() {
		return this.documentoNro;
	}

	public void setDocumentoNro(Long documentoNro) {
		this.documentoNro = documentoNro;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Short getIdInscripcionIva() {
		return this.idInscripcionIva;
	}

	public void setIdInscripcionIva(Short idInscripcionIva) {
		this.idInscripcionIva = idInscripcionIva;
	}

	public Short getIdInscripcionGanancias() {
		return this.idInscripcionGanancias;
	}

	public void setIdInscripcionGanancias(Short idInscripcionGanancias) {
		this.idInscripcionGanancias = idInscripcionGanancias;
	}
	
	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Short getIdPersonaTipo() {
		return this.idPersonaTipo;
	}

	public void setIdPersonaTipo(Short idPersonaTipo) {
		this.idPersonaTipo = idPersonaTipo;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}