package datos.recibo_pago;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import datos.persona.Persona;
import datos.recibo_pago_item.ReciboPagoItem;
import datos.usuario.Usuario;

/**
 * AbstractReciboPago generated by MyEclipse Persistence Tools
 */

public abstract class AbstractReciboPago implements java.io.Serializable {

	// Fields

	private Integer idReciboPago;

	private Persona persona;

	private Integer numero;

	private Date fechaEmision;

	private String leyenda;

	private Usuario usuario;
	
	
	private Set<ReciboPagoItem> reciboPagoItems = new HashSet<ReciboPagoItem>(0);

	// Constructors

	/** default constructor */
	public AbstractReciboPago() {
	}

	/** minimal constructor */
	public AbstractReciboPago(	Usuario usuario,
								Persona persona, 
								Date fechaEmision) {
		this.persona = persona;
		this.fechaEmision = fechaEmision;
		this.usuario = usuario;
	}

	/** full constructor */
	public AbstractReciboPago(	Usuario usuario,
								Persona persona,
								Integer numero,
								Date fechaEmision, 
								String leyenda,
								Set<ReciboPagoItem> reciboPagoItems) {
		this.persona = persona;
		this.numero = numero;
		this.fechaEmision = fechaEmision;
		this.leyenda = leyenda;
		this.usuario = usuario;
		this.reciboPagoItems = reciboPagoItems;
	}

	// Property accessors

	public Integer getIdReciboPago() {
		return this.idReciboPago;
	}

	public void setIdReciboPago(Integer idReciboPago) {
		this.idReciboPago = idReciboPago;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public String getLeyenda() {
		return this.leyenda;
	}

	public void setLeyenda(String leyenda) {
		this.leyenda = leyenda;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	public Set<ReciboPagoItem> getReciboPagoItems() {
		return this.reciboPagoItems;
	}

	public void setReciboPagoItems(Set<ReciboPagoItem> reciboPagoItems) {
		this.reciboPagoItems = reciboPagoItems;
	}
	

}