package datos.recibo_pago;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

import datos.persona.Persona;
import datos.usuario.Usuario;

/**
 * ReciboPago generated by MyEclipse Persistence Tools
 */
public class ReciboPago extends AbstractReciboPago implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	// Atributos
	private double total;
	
	public double getTotal() {
		return total;
	}
	
	public void setTotal(double total) {
		this.total = total;
	}
	
	
	/** default constructor */
	public ReciboPago() {
	}

	/** minimal constructor */
	public ReciboPago(Usuario usuario, Persona persona, Date fechaEmision) {
		super(usuario, persona, fechaEmision);
	}

	/** full constructor */
	public ReciboPago(Usuario usuario, Persona persona, Integer numero, Date fechaEmision,
						String leyenda, Set reciboPagoItems) {
		super(usuario, persona, numero, fechaEmision, leyenda, reciboPagoItems);
	}

}
