package datos.setup;

import java.util.Date;

/**
 * AbstractSetup generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSetup implements java.io.Serializable {

	// Fields

	private Integer idSetup;

	private Date fechaActualizacion;

	private String tabla;

	private Short idFacturero;

	private Long indice;

	private String observaciones;

	// Constructors

	/** default constructor */
	public AbstractSetup() {
	}

	/** minimal constructor */
	public AbstractSetup(String tabla, Long indice) {
		this.tabla = tabla;
		this.indice = indice;
	}

	/** full constructor */
	public AbstractSetup(Date fechaActualizacion, String tabla,
			Short idFacturero, Long indice, String observaciones) {
		this.fechaActualizacion = fechaActualizacion;
		this.tabla = tabla;
		this.idFacturero = idFacturero;
		this.indice = indice;
		this.observaciones = observaciones;
	}

	// Property accessors

	public Integer getIdSetup() {
		return this.idSetup;
	}

	public void setIdSetup(Integer idSetup) {
		this.idSetup = idSetup;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	public Short getIdFacturero() {
		return this.idFacturero;
	}

	public void setIdFacturero(Short idFacturero) {
		this.idFacturero = idFacturero;
	}

	public Long getIndice() {
		return this.indice;
	}

	public void setIndice(Long indice) {
		this.indice = indice;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}