package datos.facturero;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractFacturero generated by MyEclipse Persistence Tools
 */

public abstract class AbstractFacturero implements java.io.Serializable {

	// Fields

	private Integer idFacturero;

	private Date fechaAlta;

	private Date fechaVencimiento;

	private Date fechaImpresion;

	private Long numeroDesde;

	private Long numeroHasta;

	private Short puntoDeVenta;

	private Long indiceActual;

	private String razonSocial;

	private String observaciones;

	private Set contratos = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractFacturero() {
	}

	/** minimal constructor */
	public AbstractFacturero(Date fechaAlta, Date fechaVencimiento,
			Long numeroDesde, Long numeroHasta, Long indiceActual) {
		this.fechaAlta = fechaAlta;
		this.fechaVencimiento = fechaVencimiento;
		this.numeroDesde = numeroDesde;
		this.numeroHasta = numeroHasta;
		this.indiceActual = indiceActual;
	}

	/** full constructor */
	public AbstractFacturero(Date fechaAlta, Date fechaVencimiento,
			Date fechaImpresion, Long numeroDesde, Long numeroHasta,
			Short puntoDeVenta, Long indiceActual, String razonSocial,
			String observaciones, Set contratos) {
		this.fechaAlta = fechaAlta;
		this.fechaVencimiento = fechaVencimiento;
		this.fechaImpresion = fechaImpresion;
		this.numeroDesde = numeroDesde;
		this.numeroHasta = numeroHasta;
		this.puntoDeVenta = puntoDeVenta;
		this.indiceActual = indiceActual;
		this.razonSocial = razonSocial;
		this.observaciones = observaciones;
		this.contratos = contratos;
	}

	// Property accessors

	public Integer getIdFacturero() {
		return this.idFacturero;
	}

	public void setIdFacturero(Integer idFacturero) {
		this.idFacturero = idFacturero;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	public Date getFechaImpresion() {
		return this.fechaImpresion;
	}

	public void setFechaImpresion(Date fechaImpresion) {
		this.fechaImpresion = fechaImpresion;
	}

	public Long getNumeroDesde() {
		return this.numeroDesde;
	}

	public void setNumeroDesde(Long numeroDesde) {
		this.numeroDesde = numeroDesde;
	}

	public Long getNumeroHasta() {
		return this.numeroHasta;
	}

	public void setNumeroHasta(Long numeroHasta) {
		this.numeroHasta = numeroHasta;
	}

	public Short getPuntoDeVenta() {
		return this.puntoDeVenta;
	}

	public void setPuntoDeVenta(Short puntoDeVenta) {
		this.puntoDeVenta = puntoDeVenta;
	}

	public Long getIndiceActual() {
		return this.indiceActual;
	}

	public void setIndiceActual(Long indiceActual) {
		this.indiceActual = indiceActual;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set getContratos() {
		return this.contratos;
	}

	public void setContratos(Set contratos) {
		this.contratos = contratos;
	}

}