package datos.facturero;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * Facturero generated by MyEclipse Persistence Tools
 */
public class Facturero extends AbstractFacturero implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	// Constructors

	/** default constructor */
	public Facturero() {
	}

	/** minimal constructor */
	public Facturero(Date fechaAlta, Date fechaVencimiento, Long numeroDesde,
			Long numeroHasta, Long indiceActual) {
		super(fechaAlta, fechaVencimiento, numeroDesde, numeroHasta,
				indiceActual);
	}

	/** full constructor */
	public Facturero(Date fechaAlta, Date fechaVencimiento,
			Date fechaImpresion, Long numeroDesde, Long numeroHasta,
			Short puntoDeVenta, Long indiceActual, String razonSocial,
			String observaciones, Set contratos) {
		super(fechaAlta, fechaVencimiento, fechaImpresion, numeroDesde,
				numeroHasta, puntoDeVenta, indiceActual, razonSocial,
				observaciones, contratos);
	}

}
