package datos.contrato_novedad_factura;

import java.util.Date;

import datos.contrato.Contrato;
import datos.persona.Persona;

/**
 * AbstractContratoNovedadFactura generated by MyEclipse Persistence Tools
 */

public abstract class AbstractContratoNovedadFactura implements
		java.io.Serializable {

	// Fields

	private Integer idNovedadFactura;

	private Contrato contrato;

	private Persona persona;

	private Short idNovedadTipo;

	private Short periodoMes;

	private Short periodoAnio;

	private Short contratoCuota;

	private Double monto;

	private Date fechaVencimiento;

	private Date fechaAlta;
	

	// Constructors

	/** default constructor */
	public AbstractContratoNovedadFactura() {
	}

	/** minimal constructor */
	public AbstractContratoNovedadFactura(Integer idNovedadFactura,
			Persona persona, Short idNovedadTipo, Date fechaAlta) {
		this.idNovedadFactura = idNovedadFactura;
		this.persona = persona;
		this.idNovedadTipo = idNovedadTipo;
		this.fechaAlta = fechaAlta;
	}

	/** full constructor */
	public AbstractContratoNovedadFactura(Integer idNovedadFactura,
			Contrato contrato, Persona persona, Short idNovedadTipo,
			Short periodoMes, Short periodoAnio, Short contratoCuota,
			Double monto, Date fechaVencimiento, Date fechaAlta) {
		this.idNovedadFactura = idNovedadFactura;
		this.contrato = contrato;
		this.persona = persona;
		this.idNovedadTipo = idNovedadTipo;
		this.periodoMes = periodoMes;
		this.periodoAnio = periodoAnio;
		this.contratoCuota = contratoCuota;
		this.monto = monto;
		this.fechaVencimiento = fechaVencimiento;
		this.fechaAlta = fechaAlta;
	}

	// Property accessors

	public Integer getIdNovedadFactura() {
		return this.idNovedadFactura;
	}

	public void setIdNovedadFactura(Integer idNovedadFactura) {
		this.idNovedadFactura = idNovedadFactura;
	}

	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Short getIdNovedadTipo() {
		return this.idNovedadTipo;
	}

	public void setIdNovedadTipo(Short idNovedadTipo) {
		this.idNovedadTipo = idNovedadTipo;
	}

	public Short getPeriodoMes() {
		return this.periodoMes;
	}

	public void setPeriodoMes(Short periodoMes) {
		this.periodoMes = periodoMes;
	}

	public Short getPeriodoAnio() {
		return this.periodoAnio;
	}

	public void setPeriodoAnio(Short periodoAnio) {
		this.periodoAnio = periodoAnio;
	}

	public Short getContratoCuota() {
		return this.contratoCuota;
	}

	public void setContratoCuota(Short contratoCuota) {
		this.contratoCuota = contratoCuota;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

}