package datos.contrato_novedad_factura;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import app.beans.Utiles;

import datos.contrato.Contrato;
import datos.persona.Persona;

/**
 * ContratoNovedadFactura generated by MyEclipse Persistence Tools
 */
public class ContratoNovedadFactura extends AbstractContratoNovedadFactura
		implements java.io.Serializable {

	private static final long serialVersionUID = 6949231774111703570L;
	
	private String periodoCuota;
	
	// Constructors

	/** default constructor */
	public ContratoNovedadFactura() {
	}

	/** minimal constructor */
	public ContratoNovedadFactura(Integer idNovedadFactura, Persona persona,
			Short idNovedadTipo, Date fechaAlta) {
		super(idNovedadFactura, persona, idNovedadTipo, fechaAlta);
	}

	/** full constructor */
	public ContratoNovedadFactura(Integer idNovedadFactura, Contrato contrato,
			Persona persona, Short idNovedadTipo, Short periodoMes,
			Short periodoAnio, Short contratoCuota, Double monto,
			Date fechaVencimiento, Date fechaAlta) {
		super(idNovedadFactura, contrato, persona, idNovedadTipo, periodoMes,
				periodoAnio, contratoCuota, monto, fechaVencimiento, fechaAlta);
	}

	public String getPeriodoCuota() {
		
		String salida = "";
		
		try {
			if (this.getPeriodoMes() != null && this.getPeriodoAnio() != null && this.getContratoCuota() != null) {
				salida = Utiles.convertirMes(this.getPeriodoMes()) + "-" + this.getPeriodoAnio() + ". Cuota:" + this.getContratoCuota(); 
			}
		} catch(NullPointerException npe) {
			// Para q no salga null
			// npe.printStackTrace();
		}
		this.periodoCuota = salida;
		return salida;
		
	}
	
	public void setPeriodoCuota(String periodoCuota) {
		this.periodoCuota = periodoCuota;
	}
	
}
