package datos.contrato_actor;

import java.util.Date;

/**
 * AbstractContratoActor generated by MyEclipse Persistence Tools
 */

public abstract class AbstractContratoActor implements java.io.Serializable {

	// Fields

	private ContratoActorId id;
	private Date fechaBaja;
	private Double porcentaje;

	// Constructors

	/** default constructor */
	public AbstractContratoActor() {
	}

	/** full constructor */
	public AbstractContratoActor(ContratoActorId id) {
		this.id = id;
	}

	// Property accessors

	public ContratoActorId getId() {
		return this.id;
	}

	public void setId(ContratoActorId id) {
		this.id = id;
	}

	public Date getFechaBaja() {
		return fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public Double getPorcentaje() {
		return porcentaje;
	}

	public void setPorcentaje(Double porcentaje) {
		this.porcentaje = porcentaje;
	}

}