package datos.contrato_actor;

// Generated by MyEclipse Persistence Tools

/**
 * ContratoActor generated by MyEclipse Persistence Tools
 */
public class ContratoActor extends AbstractContratoActor implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;	
	
	// Constantes	
	public static short ActorTipoInquilino = 1;
	public static short ActorTipoPropietario = 2;
	
	// Constructors

	/** default constructor */
	public ContratoActor() {}

	/** full constructor */
	public ContratoActor(ContratoActorId id) {
		super(id);
	}

}
