package datos.contrato_actor;

import datos.contrato.Contrato;
import datos.persona.Persona;

// Generated by MyEclipse Persistence Tools

/**
 * ContratoActorId generated by MyEclipse Persistence Tools
 */
public class ContratoActorId extends AbstractContratoActorId implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	// Constructors

	/** default constructor */
	public ContratoActorId() {
	}

	/** full constructor */
	public ContratoActorId(Contrato contrato, Short idActorTipo, Persona persona) {
		super(contrato, idActorTipo, persona);
	}

}
