package datos.contrato;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import datos.contrato_actor.ContratoActor;
import datos.contrato_novedad_cobro.ContratoNovedadCobro;
import datos.facturero.Facturero;
import datos.inmueble.Inmueble;

/**
 * AbstractContrato generated by MyEclipse Persistence Tools
 */

public abstract class AbstractContrato implements java.io.Serializable {

	// Fields

	private Integer idContrato;

	private Inmueble inmueble;
	
	private Facturero facturero;

	private Date fechaDesde;

	private Date fechaHasta;

	private Date fechaExtension;
	
	private Date fechaRescision;

	private String observaciones;

	private Double monto;

	private Short cantidadCuota;

	private Double comisionPropPorc;

	private Double comisionPropFija;

	private Double comisionInquilino;

	private Date fechaAlta;
	
	private Boolean comercial;

	private Set<ContratoActor> contratoActors = new HashSet<ContratoActor>(0);

	private Set<ContratoNovedadCobro> contratoNovedadCobros  = new HashSet<ContratoNovedadCobro>(0);
	
	// Constructors

	/** default constructor */
	public AbstractContrato() {
	}

	/** minimal constructor */
	public AbstractContrato(Integer idContrato, Date fechaAlta) {
		this.idContrato = idContrato;
		this.fechaAlta = fechaAlta;
	}

	/** full constructor */
	public AbstractContrato(Integer idContrato, Inmueble inmueble, Facturero facturero,
			Date fechaDesde, Date fechaHasta, Date fechaExtension, Date fechaRescision,
			String observaciones, Double monto, Short cantidadCuota,
			Double comisionPropPorc, Double comisionPropFija,
			Double comisionInquilino, Date fechaAlta, Set<ContratoActor> contratoActors, 
			Boolean comercial, Set<ContratoNovedadCobro> contratoNovedadCobros) {
		this.idContrato = idContrato;
		this.inmueble = inmueble;
		this.facturero = facturero;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.fechaExtension = fechaExtension;
		this.fechaRescision = fechaRescision;
		this.observaciones = observaciones;
		this.monto = monto;
		this.cantidadCuota = cantidadCuota;
		this.comisionPropPorc = comisionPropPorc;
		this.comisionPropFija = comisionPropFija;
		this.comisionInquilino = comisionInquilino;
		this.fechaAlta = fechaAlta;
		this.contratoActors = contratoActors;
		this.comercial = comercial;
		this.contratoNovedadCobros = contratoNovedadCobros;
	}

	// Property accessors

	public Integer getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(Integer idContrato) {
		this.idContrato = idContrato;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public Facturero getFacturero() {
		return this.facturero;
	}

	public void setFacturero(Facturero facturero) {
		this.facturero = facturero;
	}
	
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	public Date getFechaExtension() {
		return this.fechaExtension;
	}

	public void setFechaExtension(Date fechaExtension) {
		this.fechaExtension = fechaExtension;
	}
	
	public Date getFechaRescision() {
		return this.fechaRescision;
	}

	public void setFechaRescision(Date fecha) {
		this.fechaRescision = fecha;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public Short getCantidadCuota() {
		return this.cantidadCuota;
	}

	public void setCantidadCuota(Short cantidadCuota) {
		this.cantidadCuota = cantidadCuota;
	}

	public Double getComisionPropPorc() {
		return this.comisionPropPorc;
	}

	public void setComisionPropPorc(Double comisionPropPorc) {
		this.comisionPropPorc = comisionPropPorc;
	}

	public Double getComisionPropFija() {
		return this.comisionPropFija;
	}

	public void setComisionPropFija(Double comisionPropFija) {
		this.comisionPropFija = comisionPropFija;
	}

	public Double getComisionInquilino() {
		return this.comisionInquilino;
	}

	public void setComisionInquilino(Double comisionInquilino) {
		this.comisionInquilino = comisionInquilino;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Set<ContratoActor> getContratoActors() {
		return this.contratoActors;
	}

	public void setContratoActors(Set<ContratoActor> contratoActors) {
		this.contratoActors = contratoActors;
	}

	public Boolean getComercial() {
		return comercial;
	}

	public void setComercial(Boolean comercial) {
		this.comercial = comercial;
	}

	public Set<ContratoNovedadCobro> getContratoNovedadCobros() {
		return contratoNovedadCobros;
	}

	public void setContratoNovedadCobros(Set<ContratoNovedadCobro> contratoNovedadCobros) {
		this.contratoNovedadCobros = contratoNovedadCobros;
	}
	
	

}