package datos.contrato;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import app.beans.Cuota;
import app.beans.NovedadTipo;
import datos.contrato_actor.ContratoActor;
import datos.contrato_novedad_cobro.ContratoNovedadCobro;
import datos.contrato_novedad_cobro.ContratoNovedadCobroProcesos;
import datos.facturero.Facturero;
import datos.inmueble.Inmueble;
import datos.persona.Persona;

/**
 * Contrato generated by MyEclipse Persistence Tools
 */
public class Contrato extends AbstractContrato implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	// Atributos
	
	/** Este atributo lo uso para saber si el contrato que esta por vencer ya fue renovado - NO SE INSTANCIA EN EL CONSTRUCTOR !!! */
	private Boolean yaRenovado;
	
	private List<Cuota> lCuotas;
	
	// Constructors

	/** default constructor */
	public Contrato() {
	}

	/** minimal constructor */
	public Contrato(Integer idContrato, Date fechaAlta) {
		super(idContrato, fechaAlta);
	}

	/** full constructor */
	public Contrato(Integer idContrato, Inmueble inmueble, Facturero facturero, Date fechaDesde,
			Date fechaHasta, Date fechaExtension, Date fechaRescision, String observaciones,
			Double monto, Short cantidadCuota, Double comisionPropPorc,
			Double comisionPropFija, Double comisionInquilino, Date fechaAlta,
			Set<ContratoActor> contratoActors, Boolean comercial) {
		
		super(idContrato, inmueble, facturero, fechaDesde, fechaHasta, fechaExtension, fechaRescision,
				observaciones, monto, cantidadCuota, comisionPropPorc,
				comisionPropFija, comisionInquilino, fechaAlta, contratoActors, comercial);
	}
	
	/**
	 * Evalua si el contrato tiene una extención, en ese caso devuelve dicha fecha
	 * Le agrego que también evalue si tiene fecha de Rescisión (4/5/2013)
	 * @return
	 */
	public Date getFin_contrato() {
		
		Date fecha_fin = this.getFechaHasta();
		
		if (this.getFechaExtension() != null) {
			fecha_fin = this.getFechaExtension();
		}
		
		if (this.getFechaRescision() != null) {
			fecha_fin = this.getFechaRescision();
		}
		
		return fecha_fin;
		
	}
	
	/**
	 * Define como se muestra un Contrato
	 * @return
	 */
//	public String mostrar() {
//		String salida = "";
//		
//		
//		
//		return salida;
//	}

	
	/**
	 * Devuelve el inquilino del Contrato
	 * @author pablo 27-08-2011
	 */
	public Persona getInquilino() {
		Persona oInquilino = null;
		Set<ContratoActor> actores = this.getContratoActors();
		for(ContratoActor oActor: actores) {
			if (oActor.getId().getIdActorTipo() == ContratoActor.ActorTipoInquilino) {
				oInquilino = oActor.getId().getPersona();
			}
		}
		return oInquilino;
	}
	
	public void setYaRenovado(Boolean obj) {
		this.yaRenovado = obj;
	}
	
	public Boolean getYaRenovado() {
		Boolean respuesta = false;
		if (this.yaRenovado != null) {
			respuesta = this.yaRenovado;
		}
		return respuesta;
	}

	public void limpiarListaCuotas() {
		lCuotas = null;
	}
	
	public List<Cuota> getCuotas() {

		if (lCuotas == null) {
			
			lCuotas = new Vector<Cuota>(); 
		
			List<ContratoNovedadCobro> dataListPago = ContratoNovedadCobroProcesos.buscarNovedadesCobroPorContrato(this, false, false);
			
			for(ContratoNovedadCobro oNovedad: dataListPago) {
				
				if (oNovedad.getIdNovedadTipo() == NovedadTipo.Alquiler) {
				
					short cuota = oNovedad.getContratoCuota();
					double monto_cuota = oNovedad.getMonto();
					short periodo_mes = oNovedad.getPeriodoMes();
					short periodo_anio = oNovedad.getPeriodoAnio();
					Date fecha_vencimiento = oNovedad.getFechaVencimiento();
					
					double saldo = oNovedad.getSaldo();
					double pagado = oNovedad.getPagado();								
					
					Cuota oCuota = new Cuota(cuota, monto_cuota, periodo_mes, periodo_anio, fecha_vencimiento);
				
					oCuota.setSaldo(saldo);
					oCuota.setPagado(pagado);
					
					lCuotas.add(oCuota);
				}
				
			}
		}
		
		return lCuotas;
	}
	
	/**
	 * Busca el número de cuota dentro del contrato
	 * @param cuota
	 * @return
	 */
	public Cuota getCuotaxNumero(short numero) {
		
		Cuota oCuota = null;
		
		// Devo validar que el número de cuota sea válido !!!!
		if (numero < 0 || numero > this.getCantidadCuota()) {
			throw new RuntimeException("Número de cuota inválido");
		}
		
		Iterator<Cuota> lista_datos = this.getCuotas().iterator();
		while (lista_datos.hasNext() && oCuota == null) {
			Cuota oCuota_ = lista_datos.next();
			if (oCuota_.getCuota() == numero) {
				oCuota = oCuota_;
			}
		}
		
		return oCuota;
		
	}
	
	
	/**
	 * Devuelve el total del CONTRATO en función de la sumatoria de CUOTAS
	 * @return
	 */
	public Double getMontoCuotas() {
		
		Double monto_cuotas = 0d;
		
		for (Cuota oCuota : this.getCuotas()) {
			monto_cuotas += oCuota.getValor();
		}
		
		return monto_cuotas;
	}
	
	
	@Override
	public String toString() {
		return "idContrato:"+this.getIdContrato();
	}
	
		
}
