package datos.usuario;
// default package



/**
 * Abstractusuario generated by MyEclipse - Hibernate Tools
 */

public abstract class Abstractusuario  implements java.io.Serializable {


    // Fields    

     private Integer idUsuario;
     private String usuario;
     private String clave;
     private String descripcion;
     private Boolean administrador;


    // Constructors

    /** default constructor */
    public Abstractusuario() {
    }

	/** minimal constructor */
    public Abstractusuario(Integer idUsuario, String usuario, String clave) {
        this.idUsuario = idUsuario;
        this.usuario = usuario;
        this.clave = clave;
    }
    
    /** full constructor */
    public Abstractusuario(Integer idUsuario, String usuario, String clave, String descripcion, Boolean administrador) {
        this.idUsuario = idUsuario;
        this.usuario = usuario;
        this.clave = clave;
        this.descripcion = descripcion;
        this.administrador = administrador;
    }

   
    // Property accessors

    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

	public Boolean getAdministrador() {
		return administrador;
	}

	public void setAdministrador(Boolean administrador) {
		this.administrador = administrador;
	}
   
}