package datos.usuario;
// default package
// Generated by MyEclipse - Hibernate Tools



/**
 * usuario generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class Usuario extends Abstractusuario implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Usuario() {
    }

	/** minimal constructor */
    public Usuario(Integer idUsuario, String usuario, String clave) {
        super(idUsuario, usuario, clave);        
    }
    
    /** full constructor */
    public Usuario(Integer idUsuario, String usuario, String clave, String descripcion, Boolean administrador) {
        super(idUsuario, usuario, clave, descripcion, administrador);        
    }
   
}
