package datos.recibo_cobro_item;

import app.beans.NovedadTipo;
import datos.contrato_novedad_cobro.ContratoNovedadCobro;
import datos.recibo_cobro.ReciboCobro;

// Generated by MyEclipse Persistence Tools

/**
 * ReciboCobroItem generated by MyEclipse Persistence Tools
 * Puede contener distintos tipos de movimientos
 */
public class ReciboCobroItem extends AbstractReciboCobroItem implements java.io.Serializable {

	private static final long serialVersionUID = -4378996756985365403L;	

	// Atributos
	@SuppressWarnings("unused")
	private String itemTipo;
	public String getItemTipo() {
		return NovedadTipo.getDescripcionCorta(this.getIdItemTipo());
	}
	
	
	// Constructors

	/** default constructor */
	public ReciboCobroItem() {
	}

	/** minimal constructor */
	public ReciboCobroItem(Integer idReciboCobroItem, ReciboCobro reciboCobro,
			Double monto, Short idItemTipo) {
		super(idReciboCobroItem, reciboCobro, monto, idItemTipo);
	}

	/** full constructor */
	public ReciboCobroItem(Integer idReciboCobroItem, ReciboCobro reciboCobro,
			ContratoNovedadCobro contratoNovedadCobro, Double monto,
			String descripcion, Short idItemTipo) {
		super(idReciboCobroItem, reciboCobro, contratoNovedadCobro, monto,
				descripcion, idItemTipo);
	}

}
