package datos.contrato_novedad_pago;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import datos.contrato.Contrato;
import datos.persona.Persona;
import app.beans.Utiles;
import app.combos.ComboImpuesto;

/**
 * ContratoNovedadPago generated by MyEclipse Persistence Tools
 */
public class ContratoNovedadPago extends AbstractContratoNovedadPago implements
		java.io.Serializable {

	private static final long serialVersionUID = -3525531554341224802L;
	
	// Atributos no persistidos - calculados
	private Double saldo;
	private String periodoCuota;
	
	// Constructors

	/** default constructor */
	public ContratoNovedadPago() {
	}

	/** minimal constructor */
	public ContratoNovedadPago(Integer idContratoNovedadPago,
			Contrato contrato, Persona persona, Short idNovedadTipo,
			Date fechaAlta) {
		super(idContratoNovedadPago, contrato, persona, idNovedadTipo, fechaAlta);
	}

	/** full constructor */
	public ContratoNovedadPago(Integer idContratoNovedadPago,
			Contrato contrato, Persona persona, Short idNovedadTipo,
			Short periodoMes, Short periodoAnio, Short contratoCuota,
			Double monto, Date fechaLiquidacion, Date fechaAlta, String observaciones,
			Short impuestoId, Short impuestoCuota, Short impuestoAnio) {
		
		super(idContratoNovedadPago, contrato, persona, idNovedadTipo,
				periodoMes, periodoAnio, contratoCuota, monto,
				fechaLiquidacion, fechaAlta, observaciones, 
				impuestoId, impuestoCuota, impuestoAnio);
	}
	
	
	public String getImpuesto() {
		
		return ComboImpuesto.getImpuesto(this.getImpuestoId());
		
	}
	
	public String getPeriodoCuota() {
		
		String salida = "";
		
		try {
			if (this.getPeriodoMes() != null && this.getPeriodoAnio() != null && this.getContratoCuota() != null) {
				salida = Utiles.convertirMes(this.getPeriodoMes()) + "-" + this.getPeriodoAnio() + ". Cuota:" + this.getContratoCuota(); 
			}
		} catch(NullPointerException npe) {
			// Para q no salga null
			// npe.printStackTrace();
		}
		this.periodoCuota = salida;
		return salida;
		
	}
	
	public void setPeriodoCuota(String periodoCuota) {
		this.periodoCuota = periodoCuota;
	}
	

	public Double getSaldo() {
		return saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}
	
	public boolean getNoLiquidada() {
		boolean respuesta = false;
		//System.out.println("CONTROL " + (this.getMonto().equals(this.getSaldo())) + " - " + this.getMonto() + ", " + this.getSaldo() );
		if (this.getMonto().equals(this.getSaldo())) {
			respuesta = true;
		}
		return respuesta;
	}
	
}