package datos.recibo_pago_item;

import app.beans.ItemTipo;
import datos.contrato_novedad_pago.ContratoNovedadPago;
import datos.recibo_pago.ReciboPago;

// Generated by MyEclipse Persistence Tools

/**
 * ReciboPagoItem generated by MyEclipse Persistence Tools
 */
public class ReciboPagoItem extends AbstractReciboPagoItem implements
		java.io.Serializable {

	// Constructors

	private static final long serialVersionUID = 1L;

	//	 Atributos
	@SuppressWarnings("unused")
	private String itemTipo;
	public String getItemTipo() {
		return ItemTipo.getDescripcion(this.getIdItemTipo());
	}
	
	
	/** default constructor */
	public ReciboPagoItem() {
	}

	/** minimal constructor */
	public ReciboPagoItem(ReciboPago reciboPago, Double monto, Short idItemTipo) {
		super(reciboPago, monto, idItemTipo);
	}

	/** full constructor */
	public ReciboPagoItem(ReciboPago reciboPago, Integer idNovedad,
			ContratoNovedadPago contratoNovedadPago,
			Double monto, String descripcion, Short idItemTipo) {
		super(reciboPago, idNovedad, contratoNovedadPago, monto, descripcion, idItemTipo);
	}

}
